### PR TITLE
Update README.md (fixing typo)

### PR DESCRIPTION
**Pull request by Rezzzort**
redFlag "reusedChaiID" > redFlag "reusedChainID"

### CODE REVIEW

**Comment by Matttioboy** [comment]
good find

**Comment by xamvic1** [comment]
nice work

**Comment by Aiham125** [comment]
Nice

**Comment by Vtalike** [comment]
Nice

**Comment by MindlessSteel** [comment]
I have a couple base NFT's and I am hoping this will help with The validation of it, because of the scammers and hackers with fake
Airdropped NFT's just like these I believe 1 is legit 🤔💭

**Comment by MindlessSteel** [comment]
Good Catch

**Comment by zerosolid** [comment]
Nice catch, boss.

**Comment by wbnns** [comment]
@Rezzzort 

Hi there! Thanks for taking the time to open this PR! I would recommend making it on the upstream repo, as this is a fork (we've pulled down the change from there). This will ensure it gets updated/fixed for everyone.

Link to upstream: https://github.com/ethereum-lists/chains

**Pull request closed without merging**
